@startuml
class WordMaker {
    + X : int <<get>>
    + Y : int <<get>>
    + Info : string <<get>>
    + Id : int <<get>>
    + WordMaker(x:int, y:int, information:string, id:int)
    + <<override>> ToString() : string
}
Shape <|-- WordMaker
@enduml
